### ISSUE TITLE
META6.json specifies an old version number for dependency for CLI::Version

### ISSUE THREAD

**Issue by frithnanth** [lizmat/CLI-Ecosystem#1]
The META6.json file for this module specifies a version number for the dependency `CLI::Version` (v0.0.5), which is not the current version of that module (v0.0.7).

**Comment by lizmat** [comment]
OOC, is this causing a problem for you?  Or are you just nudging me?  :-)

**Comment by frithnanth** [comment]
Just nudging. It's just my midsummer resolution :-)

**Comment by lizmat** [comment]
Ok.  The thing is that I pin my dependencies, because with the pinned dependencies, I know the tests worked.  And since Raku allows installation of the same module with different versions, this is a **good** thing!

Now, whenever I update a module with dependencies, I will make sure the pinning of the dependencies is also updated.  :-)

**Comment by frithnanth** [comment]
There should be a App::Mi6 extension for that ;-)
Not much of a joke: `zef rdepends` should be enough to do the trick.
